#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &


bspc config border_width         0
bspc config window_gap          10
bspc config top_padding          0

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a telegram-desktop desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# setxkbmap -option grp:alt_shift_toggle us,ru,mozc &

# autostart
killall picom
killall polybar
killall xbanish
killall dunst

picom &
# $HOME/.config/polybar/launch.sh &
$HOME/polybar-collection/launch.sh
xbanish &
killall dunst && dunst -c $HOME/.config/dunst/dunstrc &
xrdb merge $HOME/Documents/st/xresources && kill -USR1 $(pidof st)
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xsetroot -cursor_name left_ptr
tlp start

# dim screen after some time
xset s on
xset s 900

# change wallpaper and theme
wal -n -i "$HOME/Pictures/Wallpapers/p4zgr1h0mwd91.jpg"
feh --bg-fill --randomize $HOME/Pictures/Wallpapers/p4zgr1h0mwd91.jpg

# source
source ~/.fonts/*.sh

